version: "3"
services:
    kibana: 
        image: kibana:7.7.0
        ports: 
            - 5601:5601
    elasticsearch: 
        image: elasticsearch:7.7.0
        environment:
            - discovery.type=single-node
        ports: 
            - 9200:9200
    pygeoapi:
        image: geopython/pygeoapi:latest
        volumes:
            - ./configuration/local.config.yml:/pygeoapi/local.config.yml
            - ./sample-data/ne_110m_lakes.geojson:/pygeoapi/sample-data/ne_110m_lakes.geojson
        ports:
            - 5000:80


